-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 13:08:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_Clients` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `Patronymic` VARCHAR(50) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Clients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id_Cars` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(50) NOT NULL,
  `Model` VARCHAR(50) NOT NULL,
  `Year` INT NULL,
  `vin` VARCHAR(17) NULL,
  `id_Clients` INT NULL,
  PRIMARY KEY (`id_Cars`),
  UNIQUE INDEX `vin_UNIQUE` (`vin` ASC) VISIBLE,
  INDEX `1_idx` (`id_Clients` ASC) VISIBLE,
  CONSTRAINT `1`
    FOREIGN KEY (`id_Clients`)
    REFERENCES `mydb`.`Clients` (`id_Clients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Services` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `id_Services` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Time_Hours` DECIMAL(4,1) NULL,
  PRIMARY KEY (`id_Services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Parts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Parts` (
  `id_Parts` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(100) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Article` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Parts`),
  UNIQUE INDEX `Article_UNIQUE` (`Article` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Names`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_Names` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_Names` (
  `id_Order_Names` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `Total_Sume` DECIMAL(10,2) NULL,
  `Status` VARCHAR(20) NOT NULL,
  `id_Clients` INT NULL,
  PRIMARY KEY (`id_Order_Names`),
  INDEX `2_idx` (`id_Clients` ASC) VISIBLE,
  CONSTRAINT `2`
    FOREIGN KEY (`id_Clients`)
    REFERENCES `mydb`.`Clients` (`id_Clients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_In_Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Service_In_Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Service_In_Orders` (
  `id_Service_In_Orders` INT NOT NULL AUTO_INCREMENT,
  `id_Services` INT NULL,
  `Quantity` INT NOT NULL,
  `Price` DECIMAL(10,2) NULL,
  `id_Order_Names` INT NULL,
  PRIMARY KEY (`id_Service_In_Orders`),
  INDEX `3_idx` (`id_Order_Names` ASC) VISIBLE,
  INDEX `5_idx` (`id_Services` ASC) VISIBLE,
  CONSTRAINT `3`
    FOREIGN KEY (`id_Order_Names`)
    REFERENCES `mydb`.`Order_Names` (`id_Order_Names`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `5`
    FOREIGN KEY (`id_Services`)
    REFERENCES `mydb`.`Services` (`id_Services`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parts_In_Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Parts_In_Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Parts_In_Orders` (
  `id_Parts_In_Orders` INT NOT NULL AUTO_INCREMENT,
  `id_Parts` INT NULL,
  `Quantity` INT NOT NULL,
  `Price` DECIMAL(10,2) NULL,
  `id_Orders_Names` INT NULL,
  PRIMARY KEY (`id_Parts_In_Orders`),
  INDEX `4_idx` (`id_Orders_Names` ASC) VISIBLE,
  INDEX `6_idx` (`id_Parts` ASC) VISIBLE,
  CONSTRAINT `4`
    FOREIGN KEY (`id_Orders_Names`)
    REFERENCES `mydb`.`Order_Names` (`id_Order_Names`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `6`
    FOREIGN KEY (`id_Parts`)
    REFERENCES `mydb`.`Parts` (`id_Parts`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
