-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 13:28:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `id_Cars` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NULL,
  `model` VARCHAR(45) NULL,
  `license_plate` VARCHAR(45) NULL,
  `Clients_id_client` INT NOT NULL,
  PRIMARY KEY (`id_Cars`),
  INDEX `fk_Cars_Clients_idx` (`Clients_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_Cars_Clients`
    FOREIGN KEY (`Clients_id_client`)
    REFERENCES `mydb`.`Clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `id_Services` INT NOT NULL,
  `service_name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_Services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parts` (
  `id_Parts` INT NOT NULL AUTO_INCREMENT,
  `part_name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  `stock_quantity` INT NULL,
  PRIMARY KEY (`id_Parts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `id_Orders` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NULL,
  `id_cars` INT NULL,
  `order_date` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  `Clients_id_client` INT NOT NULL,
  PRIMARY KEY (`id_Orders`),
  INDEX `fk_Orders_Clients1_idx` (`Clients_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Clients1`
    FOREIGN KEY (`Clients_id_client`)
    REFERENCES `mydb`.`Clients` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Services` (
  `id_Order_Services` INT NOT NULL AUTO_INCREMENT,
  `id_service` INT NULL,
  PRIMARY KEY (`id_Order_Services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order_Parts` (
  `id_Order_Parts` INT NOT NULL AUTO_INCREMENT,
  `id_part` INT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`id_Order_Parts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders_has_Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders_has_Services` (
  `Orders_id_Orders` INT NOT NULL,
  `Services_id_Services` INT NOT NULL,
  `key` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_Orders_has_Services_Services1_idx` (`Services_id_Services` ASC) VISIBLE,
  INDEX `fk_Orders_has_Services_Orders1_idx` (`Orders_id_Orders` ASC) VISIBLE,
  PRIMARY KEY (`key`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_has_Services_Orders1`
    FOREIGN KEY (`Orders_id_Orders`)
    REFERENCES `mydb`.`Orders` (`id_Orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Services_Services1`
    FOREIGN KEY (`Services_id_Services`)
    REFERENCES `mydb`.`Services` (`id_Services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders_has_Parts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders_has_Parts` (
  `Orders_id_Orders` INT NOT NULL,
  `Parts_id_Parts` INT NOT NULL,
  `key` INT NOT NULL,
  INDEX `fk_Orders_has_Parts_Parts1_idx` (`Parts_id_Parts` ASC) VISIBLE,
  INDEX `fk_Orders_has_Parts_Orders1_idx` (`Orders_id_Orders` ASC) VISIBLE,
  PRIMARY KEY (`key`),
  CONSTRAINT `fk_Orders_has_Parts_Orders1`
    FOREIGN KEY (`Orders_id_Orders`)
    REFERENCES `mydb`.`Orders` (`id_Orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Parts_Parts1`
    FOREIGN KEY (`Parts_id_Parts`)
    REFERENCES `mydb`.`Parts` (`id_Parts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
