CREATE DATABASE IF NOT EXISTS variant2_work CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE variant2_work;

CREATE TABLE Clients (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(100),
last_name VARCHAR(100),
phone VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cars (
id INT AUTO_INCREMENT PRIMARY KEY,
clients_id INT,
brand VARCHAR(100),
model VARCHAR(100),
year INT,
license_plate VARCHAR (50),
FOREIGN KEY (clients_id) REFERENCES Clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Services (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
price DECIMAL(10,2),
duration_hours DECIMAL(5,2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SpareParts (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
price DECIMAL(10,2),
stock_quantity INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE WorkOrders (
id INT AUTO_INCREMENT PRIMARY KEY,
car_id INT NOT NULL,
order_date DATE,
status VARCHAR(50),
FOREIGN KEY (car_id) REFERENCES Cars(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE OrderServices (
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
service_id INT NOT NULL,
FOREIGN KEY (order_id) REFERENCES WorkOrders(id) ON DELETE CASCADE,
FOREIGN KEY (service_id) REFERENCES Services(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE OrderParts (
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
part_id INT NOT NULL,
quantity INT,
FOREIGN KEY (order_id) REFERENCES WorkOrders(id) ON DELETE CASCADE,
FOREIGN KEY (part_id) REFERENCES SpareParts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
